/*

 BASE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : we_game_map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __base_map_h_INCLUDE
#define __base_map_h_INCLUDE

#define base_mapWidth 20
#define base_mapHeight 32
#define base_mapBank 0

extern const unsigned char base_map[];

#endif

/* End of BASE_MAP.H */
