/*

 TEST_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 32
   Tile set      : we_game_map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __test_map_h_INCLUDE
#define __test_map_h_INCLUDE

#define TEST_MAPWidth 20
#define TEST_MAPHeight 32
#define TEST_MAPBank 0

extern const unsigned char TEST_MAP[];

#endif

/* End of TEST_MAP.H */
